AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket using a parameterized bucket name.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to be created.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: Bucket name must be lowercase and can include numbers, dots, and hyphens.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket

  S3BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
