name: CloudFormation CI
run-name: Build run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'VERSION'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - '*.sh'
      - '*.txt'
      - '*.json'
      - '.gitignore'
      - '.editorconfig'
      - '.pre-commit-config.yaml'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write


jobs:
  cloudformation-ci:
    name: CI
    uses: subhamay-bhattacharyya-gha/cfn-ci-reusable-wf/.github/workflows/ci.yaml@feature/GHA-0001-initial-release
    with:
      environment: "ci"
      cfn-directory: "cfn"
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
